views.py
from flask import flash, Blueprint, render_template, request, redirect, url_for
from models import BudgetDB, Expense, ExpenseEncoder, IncomeHistoryEncoder
import sqlite3
import json
from database import create_table_database

expenses = Blueprint('expenses', __name__)


def get_expenses_from_db():
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute("SELECT * FROM expenses")
    rows = c.fetchall()
    expenses = []
    for row in rows:
        expense = Expense(row[1], row[2], row[3])
        expense.id = row[0]
        expenses.append(expense)
    conn.close()
    return expenses


income = 0
amount = 0
income_history = []

@expenses.route('/', methods=['GET', 'POST'])
def index():
    global income, income_history
    if request.method == 'POST':
        income = float(request.form['income'])
        income_history.clear()  # Clear income history list
        income_history.append(income)  # Append income to income history list
    # Query all expenses from the database
    expenses = get_expenses_from_db()
    expenses_json = json.dumps(expenses, cls=ExpenseEncoder)

    income_history_json = json.dumps(income_history, cls=IncomeHistoryEncoder)
    # Query all budgets from the database
    budgets = get_budgets_from_db()

    # Define the total_spent() function
    def total_spent():
        conn = sqlite3.connect('database.db')
        c = conn.cursor()
        c.execute("SELECT SUM(amount) FROM expenses")
        total = c.fetchone()[0] or 0
        conn.close()
        return round(total, 2)

    # Render the index template with the expenses, budgets, and other variables
    return render_template('index.html', expenses=expenses, budgets=budgets, total_spent=total_spent(), income=income,
                           daily_spending=calculate_daily_spending(), expenses_json=expenses_json, income_history_json=income_history_json)


@expenses.route('/add_expense', methods=['GET', 'POST'])
def add_expense():
    global amount
    budgets = get_budgets_from_db()  # Retrieve budgets data from the database
    if request.method == 'POST':
        title = request.form['title']
        category = request.form['category']
        amount = request.form['amount']

        # Validate amount as a float
        global income
        try:
            amount = float(amount)
        except ValueError:
            flash('Invalid amount. Please enter a valid number.', 'error')  # Show error message
            return render_template('add_expense.html', budgets=budgets, income=income)

        if not title:
            flash('Description is required.', 'error')  # Show error message
            return render_template('add_expense.html', budgets=budgets, income=income)

        if not amount:
            flash('Amount is required.', 'error')  # Show error message
            return render_template('add_expense.html', budgets=budgets, income=income)

        if amount > income:
            flash('Expense amount cannot exceed current balance.', 'error')  # Show error message
            return render_template('add_expense.html', budgets=budgets, income=income)

        # Check if the total amount of expenses in the category exceeds the budget amount
        budget = get_budget_by_category(category)
        if budget and (get_total_expenses_by_category(category) + amount) > float(budget['amount']):
            flash('Cannot spend more money on this category. Budget limit exceeded.', 'error')  # Show error message
            return render_template('add_expense.html', budgets=budgets, income=income)

        conn = sqlite3.connect('database.db')
        c = conn.cursor()
        c.execute("INSERT INTO expenses (title, category, amount) VALUES (?, ?, ?)", (title, category, amount))
        conn.commit()
        conn.close()

        # Deduct expense amount from current balance
        income -= amount
        income_history.append(income)

        flash('Expense added successfully.', 'success')  # Show success message

    return render_template('add_expense.html', budgets=budgets, income=income)  # Pass budgets data and current balance to the template



@expenses.route('/delete_expense/<int:id>', methods=['POST'])
def delete_expense(id):
    global income
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    # Check if expense exists in the database
    c.execute("SELECT * FROM expenses WHERE id=?", (id,))
    expense = c.fetchone()
    if not expense:
        conn.close()
        return redirect(url_for('expenses.index'))

    # Delete expense from the database
    c.execute("DELETE FROM expenses WHERE id=?", (id,))
    conn.commit()
    conn.close()
    # Update income with the deleted expense amount
    income += expense[3]
    income_history.append(income)

    return redirect(url_for('expenses.index'))


def calculate_daily_spending():
    days_in_a_month = 30.4166667
    if income == 0:
        daily_spending = 0
    else:
        daily_spending = round(income / days_in_a_month)
    return daily_spending


def get_budgets_from_db():
    conn = sqlite3.connect('database.db')
    c = conn.cursor()

    budgets = []
    for row in c.execute('SELECT * FROM budgets'):
        budgets.append(BudgetDB(row[0], row[1], row[2], row[3]))

    conn.close()
    return budgets

@expenses.route('/create_budget', methods=['GET', 'POST'])
def create_budget():
    if request.method == 'POST':
        budget_name = request.form['budget-name']
        category = request.form['category']
        amount = float(request.form['amount'])

        # Check for missing inputs
        if not budget_name or not category or not amount:
            flash('Please fill in all fields.', 'error')
            return redirect(url_for('expenses.create_budget'))

        conn = sqlite3.connect('database.db')
        c = conn.cursor()

        # Check for duplicate categories
        c.execute("SELECT * FROM budgets WHERE category=?", (category,))
        existing_budget = c.fetchone()
        if existing_budget:
            flash('Budget for this category already exists. Please choose a unique category.', 'error')
            conn.close()
            return redirect(url_for('expenses.create_budget'))

        # Insert budget into the database
        c.execute("INSERT INTO budgets (budget_name, category, amount) VALUES (?, ?, ?)",
                  (budget_name, category, amount))
        conn.commit()
        conn.close()

        flash('Budget created successfully.', 'success')
    budgets = get_budgets_from_db()

    # Render the create_budget.html template with budgets data for GET requests
    return render_template('create_budget.html', budgets=budgets)

@expenses.route('/delete_budget/<int:id>', methods=['POST'])
def delete_budget(id):
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute("DELETE FROM budgets WHERE id=?", (id,))
    conn.commit()
    conn.close()
    return redirect(url_for('expenses.index'))


def get_total_expenses_by_category(category):
    conn = sqlite3.connect('database.db')
    c = conn.cursor()

    # Query the expenses table to get the total expenses for the given category
    c.execute("SELECT SUM(amount) FROM expenses WHERE category = ?", (category,))
    total_expenses = c.fetchone()[0]

    conn.close()

    # Return the total expenses for the given category
    return total_expenses or 0


def get_budget_by_category(category):
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute("SELECT * FROM budgets WHERE category=?", (category,))
    budget = c.fetchone()
    conn.close()

    # Check if budget exists for the given category
    if budget is not None:
        budget_dict = {
            'id': budget[0],
            'category': budget[2],
            'amount': budget[3]
        }
        return budget_dict
    else:
        return None

templates/add_expense.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Expense</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
    <style>
            .flash-messages {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .flash-message {
            padding: 8px; /* Padding around the message */
            margin-bottom: 10px; /* Margin bottom between messages */
            border-radius: 3px; /* Rounded corners */
            font-weight: bold; /* Bold text */
            font-size: 14px; /* Font size */
            width: 250px;
            margin-left: auto; /* Center horizontally */
            margin-right: auto; /* Center horizontally */
        }

        .flash-message.error {
            background-color: #ff8080; /* Error message background color */
            color: #ffffff; /* Error message text color */
        }

        .flash-message.success {
            background-color: #65cc71; /* Success message background color */
            color: #ffffff; /* Success message text color */
        }


            .sidebar-left {
              left: 0;
            }

            .sidebar-right {
              right: 0;
            }
        body {
            font-family: Garamond, serif;
            font-size: 27px;
            color: #FFFFFF;
            background-color: #1A1F24;
            margin: 0;
            padding: 0;
            background-image: linear-gradient(to bottom right, #111417, #1A1F24);
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 70px;
            text-align: center;
            position: relative;
        }

        img {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100px; /* Adjust height as needed */
            object-fit: cover;
        }

        .content {
            padding: 25px;
            text-align: center;
        }

        form {
            margin-top: 50px;
        }

        label, input {
            display: block;
            margin: 10px 0;
            margin-left: auto;
            margin-right: auto;
            width: 300px;
        }

         /* Example style for changing submit button color */
        input[type="submit"] {
            background-color: #111417; /* Change to the desired background color */
            color: #AD974F; /* Change to the desired text color */
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }

        /* Example style for changing submit button color on hover */
        input[type="submit"]:hover {
            background-color: #D4AF37; /* Change to the desired hover background color */
        }

        .back-button {
            display: block;
            margin-top: 20px;
            color: gold; /* Change color to gold */
            text-decoration: none;
            font-size: 24px;
            position: absolute;
            top: 20px;
            left: 20px;
        }

        .back-button:hover {
            text-decoration: underline;
        }

        /* Modify color of text, including title, labels and buttons */
        .container h1,
        .container label,
        .container button {
          color: #AD974F; /* Color for heading 1, labels, and buttons */
        }

        .container input{
           color: #000000; /* Color for input */
        }

        .container p,
        .container h3 {
          color: #F8F0E3; /* Color for paragraphs and heading 3 */
        }

    </style>
</head>
<body>
<!-- Sidebar Left -->
  <div class="sidebar-left"></div>

  <!-- Sidebar Right -->
  <div class="sidebar-right"></div>
<div class="container">
    <h1>Add Expense</h1>
    <img src="https://cdn.discordapp.com/attachments/1031582385071984723/1086949138488369202/Untitled_1.jpeg" alt="Gold Bar Image">
    <div class="content">
    <form method="POST" action="{{ url_for('expenses.add_expense') }}">
        <label for="title">Expense Description:</label>
        <input type="text" id="title" name="title">
        <label for="category">Expense Category:</label>
        <select id="category" name="category">
            <option value="None">None</option>
            {% for budget in budgets %}
                <option value="{{ budget.category }}">{{ budget.category }}</option>
            {% endfor %}
        </select>
        <label for="amount">Expense Amount:</label>
        <input type="number" id="amount" name="amount">
        <input type="submit" value="Submit" style="color: #AD974F;">
    </form>
    <a class="back-button" href="{{ url_for('expenses.index') }}">&lt;</a>
        <!-- Flash error messages -->
        {% with error_messages = get_flashed_messages(category_filter=['error']) %}
            {% if error_messages %}
                <ul class="flash-messages">
                    {% for message in error_messages %}
                        <li class="flash-message error">{{ message }}</li>
                    {% endfor %}
                </ul>
            <!-- JavaScript code to automatically hide the flash message after 3 seconds -->
            <script>
                setTimeout(function() {
                    var flashMessages = document.querySelector('.flash-messages');
                    if (flashMessages) {
                        flashMessages.style.display = 'none';
                    }
                }, 2000);  // 2 second
            </script>
        {% endif %}
    {% endwith %}

{% with success_messages = get_flashed_messages(category_filter=['success']) %}
    {% if success_messages %}
        <ul class="flash-messages">
            {% for message in success_messages %}
                <li class="flash-message success">{{ message }}</li>
            {% endfor %}
        </ul>
        <!-- JavaScript code to automatically hide the flash message after 3 seconds -->
        <script>
            setTimeout(function() {
                var flashMessages = document.querySelector('.flash-messages');
                if (flashMessages) {
                    flashMessages.style.display = 'none';
                }
            }, 2000);  // 2 seconds
        </script>
    {% endif %}
{% endwith %}
</div>



</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>PharaohFinance</title>
    <style>
      /* Table Styles */
        table {
          width: 100%;
          border-collapse: collapse;
        }
        th, td {
          border: 2px solid #AD974F;
          padding: 8px;
          text-align: left;
        }
        th {
          font-size: 18px;
          font-weight: bold;
        }
        td {
          font-size: 16px;
        }

         /* Sidebar Styles */
        .sidebar-left,
        .sidebar-right {
          background-image: url('https://cdn.discordapp.com/attachments/1031582385071984723/1086949138488369202/Untitled_1.jpeg');
          background-size: cover;
          position: fixed;
          top: 0;
          bottom: 0;
          width: 300px;
          z-index: 9999;
        }

        .sidebar-left {
          left: 0;
        }

        .sidebar-right {
          right: 0;
        }

        /* General Styles */
        body {
          font-family: Garamond, serif;
          font-size: 27px;
          color: #F8F0E3;
          background-color: #1A1F24;
          margin: 0;
          padding: 0;
        }

        .container {
        display: flex;
        max-width: 800px;
        margin: 0 auto;
        padding: 70px;
        }

        .container > div:first-child {
            margin-right: 30px;
        }

        img {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 105px; /* Adjust height as needed */
          object-fit: cover;
        }

        .content {
          margin-top: 200px; /* Adjust margin-top to leave space for the image */
          padding: 20px;
          text-align: center;
        }

        /* Add custom style for buttons */
        form button[type="submit"] {
          background-color: #111417;
          color: #AD974F;
          padding: 10px 20px;
          border: none;
          cursor: pointer;
          margin-top: 10px;
        }

        /* Optional: Add hover effect for buttons */
        form button[type="submit"]:hover {
          opacity: 0.8;
        }

        /* Modify color of text, including title, labels, inputs, and buttons */
        .container h1,
        .container label,
        .container button {
          color: #AD974F; /* Color for heading 1, labels, and buttons */
        }

        .container input{
           color: #000000; /* Color for input */
        }

        .container p,
        .container h3 {
          color: #F8F0E3; /* Color for paragraphs and heading 3 */
        }
    /* Add styles for pie chart */
    #pieChart {
        width: 400px;
        height: 550px;
        margin: 0 auto;
    }
    #lineChart {
        width: 500px;
        height: 750px;
        margin: 0 auto;
    }





    </style>

</head>
<body>
<!-- Sidebar Left -->
<div class="sidebar-left"></div>
<div style="display: flex; justify-content: center; align-items: center; margin-top: 100px; margin-bottom: 0; color: #AD974F;"> <!-- Updated margin-bottom value -->
    <h1>Pharaoh Finance</h1>
</div>
<!-- Sidebar Right -->
<div class="sidebar-right"></div>
<div class="container" style="display: flex; margin-top: -120px;">
    <!-- Left side -->
    <div style="flex: 1;">
        <h3>Income:</h3>
        <form action="{{ url_for('expenses.index') }}" method="POST">
            <label for="income">Enter your income:</label>
            <br>
            <input type="number" id="income" name="income" step="0.01">
            <br>
            <button type="submit">Submit</button>
        </form>
        {% if income > 0 %}
        <p>Balance: <span style="color: #65cc71 ">+{{ income|int }} </span>egp  </p>
        <p>Daily limit: <span style="color: #FFDF00 ">~{{ daily_spending }} </span>egp </p>
        {% else %}
        <p>No income set</p>
        {% endif %}
        <p>Total spent: <span style="color: #FF5349 "> -{{ total_spent }} </span>egp </p>
    </div>
    <!-- Right side -->
    <div style="display: flex; flex-direction: column; margin-top: 100px;">
        <div style="display: flex;">
            <div style="flex: 1; margin-right: 30px;">
                <form action="{{ url_for('expenses.add_expense') }}" method="GET" style="margin-left: auto;">
                    <button type="submit">Add Expense</button>
                </form>
                <h2>My Expenses</h2>
                <table>
                    <tr>
                        <th>Description</th>
                        <th>Category</th>
                        <th>Amount</th>
                    </tr>
                    {% for expense in expenses %}
                    <tr>
                        <td>{{ expense.title }}</td>
                        <td>{{ expense.category }}</td>
                        <td>{{ expense.amount }}</td>
                        <td>
                            <form method="post" action="{{ url_for('expenses.delete_expense', id=expense.id) }}">
                                <button type="submit" class="delete-icon" title="Delete expense" style="color: #F8F0E3"
                                        id="deleteBtn-{{ expense.id }}">X
                                </button>
                            </form>
                        </td>
                    </tr>
                    <script>
            function deleteExpense(expenseId) {
                // Disable the delete button
                var deleteForm = document.getElementById('deleteForm-' + expenseId);
                var deleteButton = deleteForm.querySelector('.delete-icon');
                deleteButton.disabled = true;

                // Make an AJAX request to delete the expense
                // ... your AJAX delete request code here ...

                // Enable the delete button after 2 seconds (adjust the timeout value as needed)
                setTimeout(function() {
                    deleteButton.disabled = false;
                }, 2000);
            }




                    </script>
                    {% endfor %}
                </table>

            </div>
            <div style="flex: 1;">
                <form action="{{ url_for('expenses.create_budget') }}" method="GET">
                    <button type="submit">Create Budget</button>
                </form>
                <!-- Budgets Table -->
                <h2>My Budgets</h2>
                <table>
                    <tr>
                        <th>Category</th>
                        <th>Amount</th>
                    </tr>
                    {% for budget in budgets %}
                    <tr>
                        <td>{{ budget.category }}</td>
                        <td>{{ budget.amount }}</td>
                        <td>
                            <form method="post" action="{{ url_for('expenses.delete_budget', id=budget.id) }}">
                                <button type="submit" class="delete-icon" title="Delete budget"
                                        style="color: #F8F0E3">X
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

</div>
<img src="https://cdn.discordapp.com/attachments/1031582385071984723/1086949138488369202/Untitled_1.jpeg"
     alt="Gold Bar Image">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<h1 style="text-align: center;">Dashboard</h1>
<div style="display: flex;">
    <div style="flex: 1; padding: 10px;">
        <!-- Render pie chart for expenses -->
        <canvas id="pieChart"></canvas>
    </div>
    <div style="flex: 1; padding: 10px;">
        <!-- Render the income history chart -->
        <canvas id="lineChart"></canvas>
    </div>
</div>

<script>
      // Get the expenses data from Flask route
      var expenses = {{ expenses_json | safe }};

      // Extract category and amount from expenses data
      var categories = expenses.map(function(expense) { return expense.category; });
      var amounts = expenses.map(function(expense) { return expense.amount; });

      // Define a variable for the grey color for "None" category expenses
      var noneCategoryColor = 'rgba(128, 128, 128, 0.2)';

      // Define an array of colors for other categories
      var otherCategoryColors = [
        'rgba(255, 205, 86, 0.5)',   // Yellow
        'rgba(147, 112, 219, 0.5)',  // Purple
        'rgba(0, 128, 128, 0.5)',    // Aqua
        'rgba(218, 165, 32, 0.5)',    // Gold
        'rgba(30, 144, 255, 0.5)',   // Dodger Blue
        'rgba(255, 140, 0, 0.5)',     // Dark Orange
        'rgba(147, 112, 219, 0.5)',  // Purple
        'rgba(0, 128, 128, 0.5)',    // Aqua
        'rgba(218, 165, 32, 0.5)',    // Gold
        'rgba(75, 192, 192, 0.5)',   // Teal
        'rgba(255, 99, 132, 0.5)',   // Red
        // Add more colors for additional categories
      ];

      // Render the pie chart using Chart.js with updated data
      var ctx = document.getElementById('pieChart').getContext('2d');
      var pieChart = new Chart(ctx, {
        type: 'pie',
        data: {
          labels: categories,
          datasets: [{
            data: amounts,
            backgroundColor: categories.map(function(category) {
              return category === 'None' ? noneCategoryColor : otherCategoryColors.pop();
            }),
            borderColor: categories.map(function(category) {
              return category === 'None' ? noneCategoryColor : otherCategoryColors.pop();
            }),
            borderWidth: 1
          }]
        }
      });

      // DOM load event listener
      document.addEventListener('DOMContentLoaded', function() {
        var incomeHistoryJSON = '{{ income_history_json|safe }}'; // Get the JSON string from Flask
        var incomeHistory = JSON.parse(incomeHistoryJSON); // Parse the JSON string into a JavaScript array

        var labels = []; // Array to store labels
        var data = []; // Array to store data

        // Loop through the incomeHistory array and populate labels and data arrays
        for (var i = 0; i < incomeHistory.length; i++) {
          labels.push('Label ' + (i + 1)); // Generate label dynamically
          data.push(incomeHistory[i]); // Get data from incomeHistory array
        }


            // Find the greatest income value
            var greatestIncome = Math.max.apply(null, incomeHistory);

        // Create a chart with Chart.js
        var ctx = document.getElementById('lineChart').getContext('2d');
        new Chart(ctx, {
            type: 'line',
            data: {
                labels: labels, // Use dynamically generated labels
                datasets: [{
                    label: 'Balance',
                    data: data, // Use dynamically generated data
                    fill: false,
                    borderColor: 'rgb(75, 192, 192)',
                    tension: 0.1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true,
                        max: greatestIncome // Set the max value to the greatest income value
                    }
                }
            }
        });
       });




</script>
</body>
</html>